name: Publish Docker Image

on:
    push:
        branches: ['main']

jobs:
    Publishing:
        name: Push Docker Image to Docker hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract Meta Data
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: muhammadasim0333/asimx-node-app

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
